real_acc:
  login: 148135748
  password: 'Codeptrai0!'
  server: 'Exness-MT5Real18'
  path: 'C:/Program Files/MetaTrader 5/terminal64.exe'
  
demo_acc:
  login: 5026881343
  password: 'IeBsW@G1'
  server: 'MetaQuotes-Demo'
  path: 'C:/Program Files/MetaTrader 5/terminal64.exe'

